version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - misspell
    - noctx
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fernandezvara/dbkit
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
